### ISSUE TITLE
CTRL-R (redo)  is not supported

### ISSUE THREAD

**Issue by ghost** [VsVim/VsVim#1177]

**Comment by xverges** [comment]
In my case, it switches to the solution explorer, even when I had it set to be handled by VsVim.

This is Visual Studio Professional 205 Update 1

**Comment by jaredpar** [comment]
@xverges can you try the following

- Tools -> Options -> Keyboard
- Put the focus in "Press shortcut keys"
- Type Ctrl+R

Do any items show up in the box below that?  If so can you list them ?

**Comment by xverges** [comment]
I get this after pressing "Reset"
![vs-kbd2](https://cloud.githubusercontent.com/assets/460418/21027238/348ac022-bd90-11e6-88aa-d8142297754e.png)


And these are the available values. No VsVim actions there...
![vs-kbd1](https://cloud.githubusercontent.com/assets/460418/21026993/42a480f4-bd8f-11e6-8d83-590f62dc3818.png)

**Comment by jaredpar** [comment]
@xverges that is strange.  For some reason the <kbd>Ctrl+R</kbd> key stroke is still bound to Solution Explorer.  VsVim must be hitting some error trying to break that key binding from that command. 

This is not completely unheard of.  Visual Studio is a bit finicky when it comes to key bindings at the API level.  Haven't had issues with that particular command though.

In order to work around this you can do the following:

- Type "View.SolutionExplorer" into the "Show Commands Containing"
- In "Shortcuts for selected command" choose the <kbd>Ctrl+R</kbd> 
- Hit the Remove Button
