### ISSUE TITLE
Undo undoes everything

### ISSUE THREAD

**Issue by jnothstine** [VsVim/VsVim#1415]
I have seen this happen only twice in the last month or two so I do not know how to duplicate the problem.  After writing a bunch of code in a C# file and doing several different changes, when I hit "u" to undo a change, everything I did in the file gets undone and the file is back to unchanged.

I am sorry I can't replicate this.  I have seen it a long time ago and it seemed to have been fixed but it is showing up again. :(

**Comment by tjcertified** [comment]
I'm not completely sure, but I believe I am still experiencing this same issue, or something close. I am unsure of the exact circumstances, but I can hit a case where I hit 'u', and it undoes 100+ changes instead of just the last change. When I try to redo, I can get to a seemingly random stopping point forward in the changelist. However, I am able to still use the forward/back arrows to continue to my latest change before the oddness occurred. I apologize for the lack of information here, but the error is more random than regular. I have ProductivityPowerTools and Resharper installed, so that might have an effect on it.

**Comment by jaredpar** [comment]
@tjcertified hmm, this scenario *should* be fairly locked down at this point.  Does this repro fairly regularly or did it happen one time only?

**Comment by tjcertified** [comment]
It is not regular, but it is also not one time only. It happened twice last week, but has not happened to me in a long time. I do remember now that I was working a lot that day with snippets, and in particular, with a snippet I had defined using Resharper's "Active Hotspot", meaning that I was dropping in and out of "external edit detected"-mode in VsVim. I'm not sure if I got all of the terminology correct there. However, it has not happened during any other typing session, only while using snippets with the active hotspots.
