### ISSUE TITLE
Issue mapping ESC to toggle in and out of insert mode.

### ISSUE THREAD

**Issue by vexe** [VsVim/VsVim#1577]
I decided to map Caps lock to toggle in and out of insert mode. But there's no way to do it from vim, so I used autohotkey to map caps lock to esc, then do the necessary mapping on esc, which worked perfectly well in gvim.

nnoremap < Esc > i // that's lower case I (i)
inoremap < Esc > < esc >l // that's lower case L, so exit out insert mode and go right. 

However in vsvim, pressing esc in normal mode to enter insert mode, will go to insert mode but then instantly go back to normal mode :(

Please see this video. Notice how I can't really get into insert mode when pressing Caps lock (or esc for that matter) - but when doing it in gvim, it works ok.

https://www.youtube.com/watch?v=wvI1rAIrcuc&feature=youtu.be

(using the the latest 1.8 vsvim)

Thank you!

**Comment by vexe** [comment]
Updated maps, forgot that < > don't play nice sometimes

**Comment by vexe** [comment]
Well I'm getting by... used F2 instead of Esc, and mapped caps to F2 via ahk. Works well. But still curious about esc

**Comment by jaredpar** [comment]
@vexe can you share out the auto hot key script that you were using?

**Comment by vexe** [comment]
Sure, a very simple:
<code>
Capslock::F2
</code>

**Comment by vexe** [comment]
I think it's not it's caps that's causing the issue, but the esc. In the video I was alternating between esc and caps, both acting the same. You could try that vim mapping of esc to toggle insert in VS, see if you get the same behaviour or is it just me.

**Comment by jaredpar** [comment]
Was able to debug this a bit tonight and I think I know what the issue is now.  It can be repro'd without the auto-hotkey script by doing the following:

- Set the key mappings exactly as you have described.
- Hit caps lock so that it is in the enabled state.
- Keep hitting escape.

The expected behavior is that it should toggle between insert / normal mode on every tap.  It does not though, it takes two taps of escape to leave insert.  

I believe that the caps lock state is confusing VsVim and causing it to only partially process the key stroke.  That is the bug that I need to fix.

**Comment by jaredpar** [comment]
BTW: this is a pretty fascinating issue to track down.

**Comment by ricksladkey** [comment]
These mappings work correctly now (VsVim 2.7.0) to toggle in and out of insert mode using only the `<Esc>` key:

```
inoremap <Esc> <Esc>l
nnoremap <Esc> i
```
