### ISSUE TITLE
Toggle does not work in Visual Studio 2015

### ISSUE THREAD

**Issue by dragn** [VsVim/VsVim#1685]
`Ctrl+Shift+F12` key combination does not toggle VsVim in Visual Studio 2015. Moreover, there is no command to toggle vim mode in `Environment->Keyboard`, search reveals only three commands related to VsVim: `VsVim.ClearTSQLBindings`, `VsVim.DumpKeyboard`, `VsVim.Options`. It would be useful to have "toggle VsVim" command that could be bound to any shortcut.
Consequently, I don't see any way to quickly toggle VsVim in Visual Studio 2015.

**Comment by jaredpar** [comment]
The <kbd>Ctrl+Shift+F12</kbd> is not actually implemented as a Visual Studio command.  Instead it's a key combination VsVim looks for directly.  That is why you don't see it show up `Environment->Keyboard` page. 

But it should work just fine in Visual Studio 2015.  I use it a couple of times a week.  

Can you check and see if any other command is bound to that keyboard combination?  

As to whether or not it could be exposed as a Visual Studio command.  I think that makes sense.  Originally it was not because it simply came online as a feature long before I supported Visual Studio commands.

**Comment by dragn** [comment]
Yeah, I looked into `VsVim->Keyboard` and `Ctrl+Shift+F12` is listed as "Handled by Visual Studio", I changed it to "Handled by VsVim" and it works. It would be nice to have it as a global command though. So it could be bound to any combination.

**Comment by ricksladkey** [comment]
This features was added a long time ago in PR #1698 for VsVim 2.1.0.

![image](https://user-images.githubusercontent.com/2680524/58923744-e010cc80-870e-11e9-9b13-8c52d754e3a9.png)
