### ISSUE TITLE
Ctrl+[ in Visual Studio Community Edition 2013 update 5

### ISSUE THREAD

**Issue by ihoro** [VsVim/VsVim#1819]
Hello,

I’ve read previous discussions of this problem and nothing helps me, it simply does nothing. And using Esc instead of Ctrl+[ "breaks entire vim concept” for me.

Do you have any idea? I can help with required details.
That’s about the latest version of the plugin in VS2013CEu5 on Win10 Home.

**Comment by rjindel** [comment]
Have you tried remapping it in the vimrc?

**Comment by phigoro** [comment]
I tried to add ‘imap’ into C:\Users\<user>\.vimrc but it didn’t help.

Somehow I recalled that en_US locale is quite special due to many things hard-coded/pre-defined/etc/etc, so I tried to switch my system back to en_US from en_GB and… and now C-[ works fine in VsVim without additional tweaking. Finally.

Let me know if you have solution for en_GB keyboard layout.

**Comment by jaredpar** [comment]
@phigoro can you see if <kbd>Ctrl+[</kbd> is bound in the Visual Studio key bindings when you have layout set to en_GB?  

- Tools -> Options 
- Environment -> Keyboard
- Type <kbd>Ctrl+[</kbd> into the "Press Shortcut Key" box

If it's bound a binding will show up in the list above.  

Unfortunately Visual Studio has different default layouts for various keyboards and locales.  It's not possible to see the layout unless I install that locale.  Over time I've found several of the other locales have bugs that I have to work around.

**Comment by rjindel** [comment]
I also found that Ctrl+Shift+F12 is by default bound to View.NextError on VS2015. I'm using UK keyboard layout.
If this is a common issue, do you think it might be a good idea to make "sticky" an issue, so there a central place to report such issues?

**Comment by jaredpar** [comment]
@rjindel didn't think that Github had sticky issues.

It's not common but it's not really uncommon either.  Probably get about one report a year on it that I need to dig into.

**Comment by phigoro** [comment]
@jaredpar Binding list is empty if I press Ctrl+[ in "Options > Environment > Keyboard > Press shortcut Keys" input box. That’s because of I previously removed all assignments related to Ctrl+[, according to [the wiki](https://github.com/jaredpar/VsVim/wiki/Troubleshooting-the-Keyboard#manually-remove-all-other-key-bindings-for-the-keystroke).

**Comment by ricksladkey** [comment]
Closing stalled investigation for Visual Studio version no longer supported.
