### ISSUE TITLE
iskeyword support

### ISSUE THREAD

**Issue by brynjolf** [VsVim/VsVim#1823]
Was wondering if iskeyword is on the roadmap as a setting? When writing unit tests I usually write names of the sort MethodName_Scenario_ExpectedOutput and it would be amazing if 'dw' would delete the method name, and not the entire tests name.

**Comment by jaredpar** [comment]
It's not currently on the roadmap but I'll add it to the backlgo.

**Comment by mgholls** [comment]
I'd really like to be able to add the - (hyphen), especially for editing PowerShell code with the Verb-Noun cmdlet naming convention

    set iskeyword+=-

**Comment by jaredpar** [comment]
Was working on abbreviations (#702) this week and came across this issue (`iskeyword` is used to describe what abbreviations are legal / illegal). Ended up thinking about this a bit because it was more complicated than I originally thought it would be. Wanted to share some thoughts I had on it. 

The `iskeyword` option is important because it defines what are legal words in vim. Today that definition is fixed and hence all of our word / WORD logic is in a `module` with stateless functions. Once we implement `iskeyword` the word / WORD logic will be stateful and tied to a specific buffer. 

This is further complicated because this logic is used in background threads via `ITextStructureNavigator`. The results of searches that involve words / WORDS are cached. This cache should be logically invalidated when the value of `iskeyword` changes. 

Thinking through this one approach seems to be:

1. Move the functions from `TextUtil` into `IWordUtil`. 
1. The `IWordUtil` type will contain and expose the implementation of `iskeyword`. The type though remains immutable hence can easily be used from multiple threads. Exposing `iskeyword` allows different instances to be compared so that our caching logic can be implemented correctly.
1. The `IVimTextBuffer` type exposes a property that returns `IWordUtil`. The `IVimBuffer` will silently update the value to a new instance every time the `iskeyword` setting changes. 

That should give us the primitives so the existing features can keep working.

**Comment by ricksladkey** [comment]
I assigned this to myself some time ago, and it is still on my to do list, and I even in fact need it for other changes I am planning for "go to definition" related to tags. The complexities you mention related to search hadn't occurred to me.

If you want tackle this feature ahead of abbreviations, you can re-assign it to yourself as I am not actively working on it yet.

**Comment by jaredpar** [comment]
The search part only occurred to me because I ended up stumbling on it while I was thinking about abbreviations. 

> If you want tackle this feature ahead of abbreviations, you can re-assign it to yourself as I am not actively working on it yet.

Okay I'll take a stab at it this weekend. It makes a bit of sense to do this work before abbreviations because it would change the implementation a bit.
