### ISSUE TITLE
relativenumbers

### ISSUE THREAD

**Issue by Ybalrid** [VsVim/VsVim#1909]
Hi,

I'm quite a fan of the vim option "relativenumber". Somebody implemented it separately in this extentensioon https://marketplace.visualstudio.com/items?itemName=BrianSchmitt.RelativeNumber&showReviewDialog=true to work with VsVim. 

Problem is, while it's working great, I think this is a functionality that VsVim should have, and that it should react like vim does regarding theses configuration variables : 

number
relativenumber

When you set number, you get normal line numbering. If you set only relative number, you get relative line number from the current cursor line (with this line being line 0) 

With both variable set, you get the absolute line number on the curent line, and relative numbers on other lines. 

Just an idea, it would be a neat feature to support. ^^"

**Comment by ricksladkey** [comment]
@brianschmitt What do you say to idea of making https://github.com/brianschmitt/relativenumber part of VsVim? The idea is apparently wildly popular!

**Comment by Ybalrid** [comment]
YES! I always install both plugin together

**Comment by ricksladkey** [comment]
@oxilumin I'm pretty sure no one is working on this and many users are eager for it to be implemented, so please continue the work to integrate the feature into VsVim. I'm glad you are looking into performance because a poor implementation could be very costly and yet only be noticeable on slow machines or large files.

**Comment by jaredpar** [comment]
I'm definitely not working on it right now either so go for it :smile:

**Comment by oxilumin** [comment]
I've finished the code for the feature itself. It seems that it's ~20-30% faster than built-in absolute line numbers margin, so there should be no performance impact.

I wanted to discuss some settings before making a PR:

1) Do we want to be able to use custom colors/font? Right not it's bound to the formatting defined for "line number" classified text (as in default line numbers margin).

2) Do we want to interact with the native line numbers margin (like hiding it when relative numbers are on)? I think we should not because somebody else might depend on/modify status of native margin or it could change in future releases of VS, so for now - we need to once disable it manually in VS settings.
On the other hand - if we replace the native margin - we get by-language customization for free. So whenever the native margin is disabled for some language - so would relative lines margin be.

**Comment by jnothstine** [comment]
I currently use a relative numbers plugin that is separate from VSVIM.  If VSVIM supports it, I will remove the plugin I have.  That plugin supports showing both the native line numbers and the relative line numbers and I really like having both.  Here is an example of what I see.

[cid:image001.png@01D4A2A2.8C9FC6B0]

Thanks for working on this!

Jerry

**Comment by ricksladkey** [comment]
@oxilumin 

> Do we want to be able to use custom colors/font?

Delegating any addition formatting of the line numbers to Visual Studio is compatible with the current version of VsVim, does the "right thing" for almost all users, and yet still permits users to customize it.

> Do we want to interact with the native line numbers margin (like hiding it when relative numbers are on)?

My preference would be to replace the existing line numbers. My reasoning is that the existing `:set number` VsVim setting already controls the default line numbers margin and the vim setting `:set number relativenumber` does not show two line number margins but a single one with the current line annotated with its non-relative number.

The alternative of supplementing the default line numbers margin requires either forcing the user to manually adjust Visual Studio to achieve compatibility with vim, or adding yet another vim-incompatible option (like `:set vsvim_bothlinemargins` in order to fully control the behavior from VsVim while providing a super-set of vim functionality.

Although not ideal, if a user (like @jnothstine) really wants both margins, continuing to use a separate extension to provide non-vim-compatible behavior seems like a reasonable trade-off.

**Comment by oxilumin** [comment]
First iteration is here: #2452

**Comment by kris10ansn** [comment]
Hi, I see that Visual Studio 2022 is added, but running `:set relativenumber` does not work for me. I am running Visual Studio 2022 for mac.
