### ISSUE TITLE
Improvment: Disabling VsVim via ctrl+shift+f12 also switches conflicting keys from "handled by vim" to "handled by windows"

### ISSUE THREAD

**Issue by cryxia** [VsVim/VsVim#1957]
Hi! I wanted to know if it is techinically possible to have this behaviour. I did a search on existing issues and didn't find an issue that was related.

If it is possible then I'll probably get it working and submit a pull request.

**Comment by ricksladkey** [comment]
When VsVim is disabled, or VsVim is not enabled for a particular window (like the output window), the way that it is supposed to work is that the fallback key processor dispatches all keys that VsVim has taken over back to the function they were originally assigned to before "Handled by VsVim" was chosen.

As a result, it already does (or at least is supposed to do) what this issue is requesting. As an example, if `<C-f>` is being handled by VsVim (for the page forward command), and you disable VsVim and press `<C-f>`, it will bring up the normal Visual Studio find window. Similarly, you can use `<C-f>` in the output window the same way, even when VsVim is not disabled.

So, in effect, `<C-f>` is indeed "handled by Visual Studio" when VsVim is disabled, as requested.

**Comment by ricksladkey** [comment]
Closing as won't fix because changing keyboard bindings is a somewhat risky and fairly resource-intensive operation that we wish to avoid if at all possible.

Any specific key that is handled by VsVim but doesn't behave as though the key were handled by Visual Studio when VsVim is disabled should be reported as a separate issue.
