### ISSUE TITLE
Commands sometimes appear in the source code 

### ISSUE THREAD

**Issue by CaseyChesshir** [VsVim/VsVim#2170]
Hello, 

I'm not sure what the intent is or what's really going on but I intermittently experience this problem where my vim commands end up in this white box in visual studio. I was trying to ctrl+c and then undo some things but the command gets inserted where my cursor was. I haven't figured out how to get rid of it without closing visual studio. 

If this is actually a feature I'd like to know what it's for. 

![image](https://user-images.githubusercontent.com/10947257/40802895-c6c19702-64cb-11e8-9f6a-e20deec1a7c1.png)

**Comment by ricksladkey** [comment]
The white box is intended only for display purposes, because Visual Studio (unlike vim) does not render control characters present in the file. So you are *supposed* to see one white box for each control character.

So somehow you accidentally inserted a control character, presumably while typing it in insert mode. If this happens, you should be able to type `<Esc>` to exit insert mode and `u` to undo the insert or move the caret before the control character and type `x` to delete it like any other character.

So that's the background information. However, the explanation is inconsistent with the symptoms you are reporting because I don't doubt you tried to press `<Esc>`. Furthermore, the presence of the `uuuuu` characters, none of which are control characters, means something has gone horribly wrong. From looking at the code, I don't immediately see how that could happen.

**Comment by ricksladkey** [comment]
A little more research shows that the `^C` glyph is actually a text box and that if you manage somehow to give it the focus, you can type into it. The workaround is to click *outside* the `^C` with the mouse and then you can hit `<Esc>` and `u`, as you were originally intending. The long-term solution is to not allow the glyph to accept the focus.

**Comment by ricksladkey** [comment]
Fixed in PR #2531.

**Comment by CaseyChesshir** [comment]
@ricksladkey thank you!
