### ISSUE TITLE
Insert Mode - CTRL-N, CTRL-P

### ISSUE THREAD

**Issue by jaredpar** [VsVim/VsVim#246]
Lexical match completion

**Comment by luoxz** [comment]
In vim, once you have triggered one type of completion (lexical, line, dictionary, file...), then CTRL-N and CTRL-P navigate in that completion.
In VsVim CTRL-N and CTRL-P always trigger the lexical completion. Even when there is already an "intellisense" completion open (the one triggered with this.). It should navigate in the "intellisense" instead of opening the lexical completion.

**Comment by luoxz** [comment]
Ctrl+n and Ctrl+p OR  Tab

**Comment by luoxz** [comment]
Navigating intellisense with Ctrl+N and Ctrl+P  OR Tab Select Option , 
he wants to use ctrl-n and ctrl-p to go down and up through the list instead of reaching over to hit the arrow keys.

**Comment by luoxz** [comment]
inoremap <C-p>      <up>
inoremap <C-n>      <down>
set failure，Not working(Navigating intellisense   , Ctrl+N and Ctrl-P)

**Comment by luoxz** [comment]
inoremap <C-p> <up>
inoremap <C-n> <down>

**Comment by luoxz** [comment]
inoremap `<C-p>`      `<up>`
inoremap `<C-n>`     `<down>`

**Comment by luoxz** [comment]
inoremap `<C-p>` `<up>`
inoremap `<C-n>` `<down>`
set failure，Not working(Navigating intellisense , Ctrl+N and Ctrl-P)

**Comment by jaredpar** [comment]
@luoxz the behavior in VsVim is for those keys to navigate the open completion session.  It should not end the session.  I think it's likely something specific to your setup that is causing this.  Items to check: vimrc contents and if these are listed as causing completion in the editor options.

**Comment by luoxz** [comment]
Thank you very much for jaredpar，My question is the same 

 #1149


jaredpar commented on 15 Aug 2013
I have looked into doing this and it's pretty reasonable to implement. There is one behavior though that this will change.

Today in Visual Studio if you press Ctrl while Intellisense is up the window will fade. The intent is to let you view the code which is hidden by the window. If I implement this feature I will necessarily have to simply disable this feature. Otherwise you'd have the window constantly fading in and out while you were attempting to scroll. I doubt this is a big deal but wanted to let people know.

Intellisense 

Ctrl +n    and Ctrl+p  
Replaced
Tab      and   Shift + Tab

**Comment by luoxz** [comment]
Intellisense

Ctrl +n and Ctrl+p

Replaced     Vim

Tab and Shift + Tab

**Comment by keithn** [comment]
For autocomplete In visual studio keyboard bindings I used ALT-J and ALT-H to go up and down.....  in resharper ctrl doesn't make the auto complete go away but ALT-ALT does (which is useful).   

However, other resharper windows don't seem to respect those binding ( like goto usages, or goto type )   I have an open issue with jetbrains for this.

**Comment by BlueInt32** [comment]
@keithn can you tell what are the names of the bindings in visual studio keyboard settings ("next element in intellisense") ? Thanks

**Comment by simon-budin** [comment]
For anyone interested, the quick actions popins can be navigated with TAB key.
