### ISSUE TITLE
Ctrl-[ (and bunch of other keys) handling control on the Czech keyboard does not show up in the config

### ISSUE THREAD

**Issue by risa2000** [VsVim/VsVim#2461]
I have just installed 2.6.0.0 into VS 2017 Community. I am using keyboard with "Czech" layout (Win 10 64 bit). When I installed the extension, I was presented with the list of keyboard commands where I could choose which one I let VS handle and which one I let VsVim handle.

I chose to let all have handled by VsVim, but then when trying to use `Ctrl-[`, which on the Czech layout maps to `Ctrl-ú` key (it is the same key, but types a different character), but is normally recognized as `Ctrl-[` in the regular `vim` for example, I got the notification from VS

> (Ctrl+ú) was pressed. Waiting for second key of chord

After searching the issues here and the wiki I indeed found out that there is a bunch of double stroke commands bound to `Ctrl-ú` in VS keyboard shortcuts. What however was strange that wiki here mentioned that the mapping for `Ctrl-[` should be advertised in VsVim mapping config, but it was not.

After I changed my keyboard layout to "English US" the mappings in VsVim config suddenly appeared and where all set to "Visual Studio". There were `Ctrl-[`, `Ctrl-]`, and few others.
After I set all the remaining mappings to have "VsVim" handling the keys started to work ok. They work fine even when I switch my keyboard layout back to "Czech".

I guess there is some problem with initial VsVim keys detection where it may query Visual Studio for `Ctrl-[` mappings, but VS returns none, because it recognizes this key press as `Ctrl-ú`, so VsVim assumes this is fine and does not offer the mapping override in the config menu. Once the collision is detected (by switching to "English US" layout) by VsVim it offers the remap and remembers it from that time on.

The easiest workaround seems to switch to "English US" layout before first running VsVim. The better solution would be to run the collision check in VsVim based on the keyboard layout, i.e. on the actual keycodes and not on the graphical similarity of the characters, but I do not know if it is possible.

**Comment by jaredpar** [comment]
Thanks for filing the detailed issue here. 

Can you do the following: 

1. Reset the keyboard settings in Visual Studio (Tools -> Options -> Keyboard -> Reset) 
1. Open the command window
1. Run the command VsVim.DumpKeyboard

That print out a file name. Could you post / email the contents of that file? It contains diagnostic dump of how VS is setting up the keyboard shortcuts on your machine. It will help me understand if there is something I can do here. 

Part of the problem here is that VS does keyboard shortcuts based on virtual key codes, not the characters that are produced from the virtual key codes. While vim, and VsVim, tend to do the opposite and focus on the produced characters. On English keyboards the mapping between virtual key codes and characters is pretty 1:1 hence VsVim _works_ in that environment at detecting conflicting keys. On non-English keyboards though the key mappings are not 1:1 and hence the conflict detection code falls over. I've attempted a few times to map vitrual key codes to characters and add that to conflict detection but it hasn't been as successful as I would've liked.

**Comment by risa2000** [comment]
I did the dump and posted it here https://pastebin.com/raw/6cMtNQUE
It turned out I had to "Reset" the mappings in the "Options" and then **restart VS** otherwise the key mappings were still held by VsVim.

However I am still a bit confused about what exactly the "Reset" resets, because I am pretty sure I added definition for `F11` key (as `Debug.StepInto`) after I installed VS and after the reset this mapping is still preserved. VsVim mappings seem to be reverted though.

Another strange thing is that after the reset the VsVim mapping config shows that the commands `Ctrl-[`, `Ctrl-]`, `Ctrl-Shift-[`, and `Ctrl-Shift-]` are still handled by VsVim, even though it is not true (https://imgur.com/eNKVkdl). When I press `Ctrl-ú` (the same key on the Czech keyboard as `Ctrl-[` on the US keyboard) I got the already mentioned prompt:

> (Ctrl-ú) was pressed. Waiting for second key of chord...

I guess the reported settings gets mixed up because my layout is Czech and VsVim does not recognize `Ctrl-ú` as `Ctrl-[`.

**Comment by ricksladkey** [comment]
Sorry if this is work you think you've already done, but I'm pretty sure (as you are) that the keyboard reset did not "work as we had hoped".

Can you do the following:

- Reset all VsVim keyboard settings to "Handled by Visual Studio"
- Reset the keyboard settings in Visual Studio (Tools -> Options -> Keyboard -> Reset)
- Check something that you are sure about like `F11` is properly reset (restarting Visual Studio if necessary)
- Open the Visual Studio Command Window
- Run the command `VsVim.DumpKeyboard`

**Comment by risa2000** [comment]
I followed your points, but for some reason the `F11` key remains to be mapped to `Debug.StepInto`. I tried switching to different mapping schemes (e.g. Default, Visual Studio Code, or Visual C++ 6) and pressing `Reset`  in between, with (or without) restarting VS, but `F11` would not budge.

So either when I originally mapped it, I actually just put in the "default" mapping, or the resetting does not work. Unfortunately, I cannot confirm either as I do not remember changing any other mapping.

FWIW, at the end I set the Default scheme, did one final reset and dumped the keyboard mapping: 
https://pastebin.com/raw/LedPhJML

**Comment by ricksladkey** [comment]
Thanks, @risa2000. I came up with a fix for your other problem. I will look at this one soon.

**Comment by ricksladkey** [comment]
OK, so for the key binding dump you reported, `Ctrl+[` is not mapped by Visual Studio, which is a good thing because on the Czech keyboard layout, `[` is an `AltGr` key, and so it is not possible to add the `Ctrl` modifier to the `[` key, because it already has the `Ctrl+Alt` modifiers. The `Ctrl+[` keystroke combination does not show up in the VsVim keyboard configuration because it does not conflict with any Visual Studio binding.

On the other hand, the `Ctrl+ú` keystroke combination **does** appear in the key binding dump and so it **should** appear in the keyboard configuration if and only if you have that key combination mapped in your VsVim rc file. I am guessing that you did **not** have that mapped in your rc file, and so `Ctrl+ú` did not appear in the VsVim keyboard configuration either.

So here we have an unusual situation: VsVim does not know that when `Ctrl+ú` is pressed in a console application like vim, that ASCII `0x27 / ESC` would be generated. As it result, it does not proactively realize that the composite Visual Studio keystroke `Ctrl+ú` conflicts with its traditional role of generating ASCII `0x27 / ESC` on the Czech keyboard.

At the moment, the only solution is for the user to realize that Visual Studio uses that key for other purposes and as a result does one of the following:

1. Manually remove any key bindings involving `Ctrl+ú` using Tools -> Options -> Environment -> Keyboard (and restart Visual Studio if it contains any "chord" bindings) as described in the FAQ, or
2. Map `Ctrl+ú` in their VsVim rc file, (e.g. `:map <C-ú> <Esc>`) and the close and restart Visual Studio, and finally, then choose "Handled by VsVim" for `Ctrl+ú` in the VsVim keyboard configuration

In fact, the former solution will only work in VsVim 2.7.0, not VsVim 2.6.0 as reported in your other issue #2462) so to use that approach you would have to use VsVim from the VsixGallery (as described in the FAQ) or wait for VsVim 2.7.0.

I think the latter solution will work for VsVim 2.6.0 or later. However, it is not ideal for you to have to create a mapping for this key because, as we know, on the Czech keyboard it already would generate ASCII `0x27 / ESC` and vim does not need a mapping for it to work. The purpose then, of the mapping, is simply to get the keystroke to appear in VsVim's keyboard configuration.

The only better solution I can think of would be for VsVim to be able to know which keys generate which ASCII control characters with the current keyboard layout and then to include those keys to the keyboard conflict settings. Whether this is even possible is a separate question, but even if it is possible, it is beyond VsVim's current capabilities.

This long explanation is by way of saying that I do not believe there is any bug in VsVim that needs fixing; what was needed is to explain why VsVim is behaving the way it does in this situation.

**Comment by risa2000** [comment]
> This long explanation is by way of saying that I do not believe there is any bug in VsVim that needs fixing; what was needed is to explain why VsVim is behaving the way it does in this situation.

Rick, thanks for indeed a lengthy explanation. I am not going to question the feasibility of the "fix" in the VsVim that I leave up to you, but I would like to throw in a different opinion on how the keys actually behave and why I believe the VsVim does not behave correctly.

The "bracket" key (`[`) on US/English layout and `ú` key on Czech layout are physically the same key. I.e. the 12th key in the 2nd row. I have been typewriting for 25 years, so I can appreciate the importance of the keyboard layout. I do not know when or who at Microsoft decided that `Ctrl` combinations were not translated literally in localized layouts but by the layout. If I knew, I would personally congratulate this person, because he actually made my life on the Czech keyboard great.

The thing is that `Ctrl` keys (i.e. `Ctrl-<key>` combos) have no direct relation to the graphical symbols on the very same keys. I.e. `Ctrl-C` is `Break`, `Ctrl-D` is `EOF`, and `Ctrl-[` is `ESC`, but it really does not matter that the letters on these keys are `C`, `D`, or `[`. Of course because historically everything started with the US keyboard (layout), the `Ctrl` keys were also referred by theirs *character codes*. This was however just a shorthand for not needing saying things like the 12th key in the 2nd row.

What Microsoft has realized that while the graphical symbols (characters) can get reshuffled on localized layouts they understood that it would not work for `Ctrl` keys, because, for example as you yourself found out the symbol `[` is on the Czech keyboard written as `AltGr+F`, and because `ESC` has no stronger relation to either `[` or `F` **they localized the `Ctrl` keys by layout**. (Also it does not make much sense to provide a three-key combo as a shorthand for a popular control code.)

On the side note, the linux people did not get the same understanding of how the layout works, and did the localization literally (by the characters on the keys), i.e. in `gVim` in Ubuntu, to type `ESC` you have to type `Ctrl+AltGr+F` and it works! It does not make sense though.

It is clear that the Visual Studio respects this "localization by layout" for `Ctrl` keys, so where it shows the bindings using `Ctrl-ú` while using the Czech layout, it shows `Ctrl-[` for the very same binding when the keyboard switches to the US layout.

In other words, it just shows a hint to the user, which keys it expects the user to press, not which char code, this should generate. For sure, the char code of `ú` is different from the char code for `[`, but this technically does not matter when these _keys_ are combined with `Ctrl`. Needless to say that in `vim` (`gvim`) on Windows `Ctrl-ú` / `Ctrl-[` work as expected in the respective layouts and I would assume it works in the other keyboard layouts too, and, analogically VsVim would have the similar problems in the other keyboard layouts.

All this to just say that I do not know how VsVim should (or if could) do it, but I know, that it should not compare the `Ctrl` mappings on the level where the symbol representations (character codes) matter, but on the level where the keyboard layout (scan codes?) are processed. Because it is exactly what Visual Studio does when it shows the same binding as `Ctrl-ú` in Czech layout and `Ctrl-[` in English layout.

**Comment by ricksladkey** [comment]
@risa2000, you have summarized the situation nicely and pointed out that Visual Studio stores its keybindings as "scan codes" (or more accurately as WPF keys) and that it converts those scan codes into key names when displaying them to the user. So:

- When Visual Studio says `Ctrl+ú` with the Czech keyboard layout, it means "hold control down while pressing the key to the right of the `P` key"
- But it will change to saying `Ctrl+[` when you switch (on the fly) to the US keyboard layout because it also means "hold control down while pressing the key to the right of the `P` key"

But gvim and VsVim do not behave this way: the key bindings that are in effect do not depend on the keyboard layout. For example take the characters `Z` and `Y`, which are swapped on the Czech keyboard relative to the US keyboard. In vim and VsVim, if you switch the keyboard layout on the fly, and want to press `<C-z>` or `<C-y>` you have to press a different physical key.

In summary, if you switch the keyboard layout "on the fly":

- Visual Studio keybindings will stay attached to the same physical key
- vim and VsVim keybindings will move to the whatever physical key produces the logical key

What this means is that which keys conflict between Visual Studio and VsVim will very likely change when you change keyboard layouts on the fly. This means that key conflict detection is extremely dynamic and error prone. It means that if you switch keyboard layouts frequently, you will have to manage the conflicts yourself, rather than letting VsVim try to manage them for you. Or at least be aware that the VsVim keyboard conflict management is applicable to the keyboard layout that was in effect when it last tried to resolve them.

The safest thing to do is to always perform VsVim keyboard conflict resolution with the keyboard layout that you normally use, and then live with (or manually resolve) any conflicts that arise when you switch keyboard layouts on the fly.

**Comment by ricksladkey** [comment]
At the risk of beating a dead horse, I would like to reiterate that Visual Studio (unlike vim and VsVim) pays no attention to ASCII control characters. For example on the US English keyboard, you cannot use the <kbd>Ctrl</kbd>+<kbd>[</kbd> key to dismiss modal windows, even though that key combination will generate ASCII `0x27 / ESC`. Likewise, on the Czech keyboard, you cannot dismiss modal windows using the <kbd>Ctrl</kbd>+<kbd>[</kbd> key, even though that key combination will generate ASCII `0x27 / ESC`. But vim and VsVim **will** understand any key combination that generates ASCII `0x27 / ESC` as a vim `<Escape>` key.

This is a separate (but important) related topic and the bugs related to that problem were addressed in issue #2462 and PR #2516.

**Comment by risa2000** [comment]
@ricksladkey I have read your comment on https://github.com/VsVim/VsVim/pull/2516#issue-275528735 and it does much more sense to me now. Thanks for that. I have also not realized before that `vim` actually uses "the literal translation" for the `Ctrl` keys, and you are right, `Ctrl-Z` moves around the layout with the symbol `Z`.

The only mystery is, how does the regular `vim` recognize `Ctrl-ú` correctly as `ESC`.

**Comment by risa2000** [comment]
> At the moment, the only solution is for the user to realize that Visual Studio uses that key for other purposes and as a result does one of the following:
> 
> 1. Manually remove any key bindings involving `Ctrl+ú` using Tools -> Options -> Environment -> Keyboard (and restart Visual Studio if it contains any "chord" bindings) as described in the FAQ, or
> 2. Map `Ctrl+ú` in their VsVim rc file, (e.g. `:map <C-ú> <Esc>`) and the close and restart Visual Studio, and finally, then choose "Handled by VsVim" for `Ctrl+ú` in the VsVim keyboard configuration

One more thing. You mentioned two different approaches above. I am not sure if it contains what I did originally to fix this issue on my setup:

I switched the keyboard layout to the US layout, run VS and VsVim config for mapping, where all the conflicting combinations suddenly appeared (i.e. `Ctrl-[`, `Ctrl-]`, etc.). I assigned them to VsVim, then switched back the keyboard to the Czech layout and the `Ctrl-ú` worked as expected.

I guess it is probably what you describe in your first point, except I did not do it manually, but VsVim removed all `Ctrl-ú` mappings in VS when they were presented in the English layout as `Ctrl-[` and reassigned to VsVim.

**Comment by ricksladkey** [comment]
> The only mystery is, how does the regular `vim` recognize `Ctrl-ú` correctly as `ESC`.

Ha, ha, it is no mystery: on the Czech keyboard, layout `Ctrl-ú` generates `0x27 / ESC` and both vim and VsVim recognize `0x27 / ESC` as `<Escape>`! But VsVim won't ever see that keystroke if it has a binding in Visual Studio.

Let me try to describe it another way: conceptually vim does nothing more than call `getchar()` on standard input and, voila, it receives a character `0x27 / ESC`. How and why that happens in entirely a result of the keyboard layout and requires no work or special handling on vim's part.

**Comment by risa2000** [comment]
> Ha, ha, it is no mystery: on the Czech keyboard, layout `Ctrl-ú` generates `0x27 / ESC` and both vim and VsVim recognize `0x27 / ESC` as `<Escape>`! But VsVim won't ever see that keystroke if it has a binding in Visual Studio.

Ha, since the `vim` help refers to them as `<ESC>` or `Ctrl-[` I did not realize that the code it receives when pressing the `Ctrl-[` (on Windows) is actually really `<ESC>` and not `Ctrl-[`. Thanks again for another insight.
