### ISSUE TITLE
Neither Ctrl-V not Ctrl-Q quote Ctrl characters or the escape key

### ISSUE THREAD

**Issue by vhe1** [VsVim/VsVim#2467]
Hi!
Maybe I just haven't found this in the documentation yet, but I find myself unable to devine macros with the Esscape key or any other not-standard keys in them.
On Unix, Ctrl-V used to be the "insert the next character literally", like Escape or Ctrl-M. On windoes gvim. it's either Ctrl-V (vi mapping) or Ctrl-Q (windows mapping).

So, how do I put an Escape-Character or Return or a control character in a macro (i.e in the colon mode) using vsvim?
like for prepending a line with a text and moving to the next line
:map v Icooltext<Escape?>j
or, for, say, splitting the records of a .csv
: %s/,/<Return?>/g

**Comment by jaredpar** [comment]
Thanks for taking the time to file this.

I thought we had a bug for the <kbd>Ctrl-V</kbd> case but I can't find it. Lets use this bug as the general support bug here for the feature.

**Comment by sqlkoala** [comment]
Hi, that is no problem, there is a special notation for this:
:map v Icooltext<Esc>j

Return is <CR>.

**Comment by sqlkoala** [comment]
Hello again, sorry I can't write posts with code in them because my chrome / FF are not supported. I will try once more.
Escape is <  (less then) Esc > (greater then). Without spaces. Return is CR.

**Comment by vhe1** [comment]
Ok. Thanks a lot! :-)

**Comment by ricksladkey** [comment]
To expand on what @sqlkoala said, it is definitely possible to use mappings or regular expressions with special characters even though they cannot currently be quoted with `<C-v>`. In mappings you can use `<Esc>`  instead of typing `Ctrl+V Escape` and in regular expressions you can type `\r` instead of `Ctrl+V Enter`. These notations are also supported by vim.

**Comment by ricksladkey** [comment]
To summarize this issue, it is almost never a good idea to place literal ASCII control characters in a text file if you do not have to, and you never have to in a vim rc file, because you can always use notation to refer to ASCII control characters (or other key combinations for that matter).

However, in some rare cases you really need to insert literal ASCII control characters in a text file. In those cases, vim allows you to use <kbd>Ctrl</kbd>+<kbd>V</kbd> in insert mode to enter them:

From `:help i_CTRL-V`:

> CTRL-V
> 		Insert next non-digit literally.  For special keys, the
> 		terminal code is inserted.  It's also possible to enter the
> 		decimal, octal or hexadecimal value of a character
> 		|i_CTRL-V_digit|.
> 		The characters typed right after CTRL-V are not considered for
> 		mapping.  {Vi: no decimal byte entry}
> 		Note: When CTRL-V is mapped (e.g., to paste text) you can
> 		often use CTRL-Q instead |i_CTRL-Q|.
