### ISSUE TITLE
VsVim hanging Visual Studio 2019

### ISSUE THREAD

**Issue by howardlo** [VsVim/VsVim#2489]
First let me thank Jared and the team for a fantastic tool! 

I've noticed that VsVim slowing substantially to the point of being close to unusable in VS2019. It's been this way since Feb for the preview and RC versions. I was hoping it got better as it approached release but sadly it hasn't improved.

Please tell me how I can help try to debug or fix it. Thanks!

![Capture](https://user-images.githubusercontent.com/9260138/56088616-3eb97880-5e39-11e9-9257-ea3c5022d4c3.PNG)

**Comment by jaredpar** [comment]
Unfortunately this is typically a bug on Visual Studio's part where they are mis-diagnosing VsVim as the perf problem. I've seen this myself a number of times and every case I've worked through has turned out to be a bug elsewhere. They have identified the problem and are looking to make a fix in Update 1. 

That being said, it's certainly possible that there are bugs in VsVim here. If you see a significant perf difference between VsVim being enabled and disabled then that's definitely something to dig into. In that case can you do see this please grab a perf trace and share it out. I can dig through and see what is going on with that.

> https://github.com/dotnet/roslyn/wiki/Recording-performance-traces-with-PerfView

**Comment by howardlo** [comment]
Thanks Jared!

And thanks for the PerfView hint.

Howard

**Comment by ricksladkey** [comment]
VsVim is currently available for download in the extension gallery for VS2019 and so many, many users besides the developers are using it successfully. It is definitely possible that VsVim is only causing slowdowns leading to a hang on some machines. But without more information or being able to reproduce the problem, we cannot really make any headway on this issue.

@howardlo, if you get a chance to collect a perf trace or can find a repro, please add it to this issue and I'll reopen it.
