### ISSUE TITLE
verbatim strings break block commands di) da)

### ISSUE THREAD

**Issue by CrispyDrone** [VsVim/VsVim#2504]
This issue is similar to this one: https://github.com/jaredpar/VsVim/issues/2159

In this case however it happens when a verbatim string is used. For example, attempting to use `di)` or `di(` or any similar command will not work with VsVim, but it does inside vim.

```
if (Directory.Exists(myDirectory + @"\" + mySubDirectory))
```

**Comment by ricksladkey** [comment]
The current situation with VsVim is that although it doesn't handle verbatim strings that end with `\", it does handle all other strings (that possibly contain mismatched) parentheses better than vim does (see issue #2159).

Since verbatim strings are a C# specific feature and since VsVim current string handling is based on the "universal" programming string (single or double quotes using backslash to quote quote characters), I think the current behavior is a good compromise which works the same in all programming languages.

However, as a feature request, we could certainly detect that the current language service is C# and extend the current "universal" string handling to also support C# verbatim strings.

**Comment by CrispyDrone** [comment]
I see. Thanks for your reply. I also wanted to quickly say that I really love this extension and immensely appreciate the work that goes into it!
