### ISSUE TITLE
VsVim remap ctrl-i (`<c-i>`) is ignored

### ISSUE THREAD

**Issue by EdwinVanRooij** [VsVim/VsVim#2532]
I want to see quick info on keypress control+i in normal mode. In order to accomplish this, I'd assume I'd have to use the following mapping:
`nnoremap <c-i> :vsc Edit.QuickInfo<cr>`

This mapping seems ignored however. To verify the mapping syntax is correct, I've used this mapping to verify:
`nnoremap <c-h> :vsc Edit.QuickInfo<cr>`

Using that mapping, ctrl+h in normal mode (as opposed to ctrl+i in normal mode) does show quick info. Ctrl+i (info) seems to make more sense to me though, so I'd really like to map I instead.

What DOES happen on ctrl+i: The text on the current line (where my cursor is at), moves 4 spaces to the right. 

Other mappings I've tried without fortune:
```
nnoremap <c-i> :vsc Edit.QuickInfo<cr>
nnoremap <C-i> :vsc Edit.QuickInfo<cr>
nnoremap <c-I> :vsc Edit.QuickInfo<cr>
nnoremap <C-I> :vsc Edit.QuickInfo<cr>
nnoremap <c-s-i> :vsc Edit.QuickInfo<cr>
nnoremap <C-s-i> :vsc Edit.QuickInfo<cr>
nnoremap <c-s-I> :vsc Edit.QuickInfo<cr>
nnoremap <C-s-I> :vsc Edit.QuickInfo<cr>
nnoremap <c-S-i> :vsc Edit.QuickInfo<cr>
nnoremap <C-S-i> :vsc Edit.QuickInfo<cr>
nnoremap <c-S-I> :vsc Edit.QuickInfo<cr>
nnoremap <C-S-I> :vsc Edit.QuickInfo<cr>
```

Note: Only `<c-i>` results in the 4 spaces addition. For example, `<c-s-i>` does nothing.

The complete .vimrc I'm using:
[vimrc.txt](https://github.com/VsVim/VsVim/files/3156841/vimrc.txt)

Any suggestions to fix this would be greatly appreciated.

**Comment by EdwinVanRooij** [comment]
Ahhh yeah that explains it. I never would've thought that (presumably) the OS (windows) actually makes a difference between different letter-combinations with the control button.

As this is out of the extension's reach, I'll close this issue.

For those who may stumble upon a similar problem, this is the workaround that I'll use:

--> Install autohotkey (I already have a script on system boot running, so it's only a minor addition to me)
--> add the line `^i::^h` (this will map ctrl+i to ctrl+h which IS remappable in your `.vimrc`)
--> add the line `nnoremap <c-h> :vsc Edit.QuickInfo<cr>` to your `.vimrc`
--> run the autohotkey script

Now, the following will happen when I want parameter info in my IDE:
1. I press ctrl+I
1. AutoHotKey will catch the ctrl+I key press event, and convert it to ctrl+h instead
1. Visual studio has no mappings on ctrl+h, so it will pass the key press event to VsVim
1. VsVim will notice I have ctrl+h mapped to Edit.QuickInfo and show me the info

For the end user, me, I'll just press ctrl+i for info. The configuration gets a little dirty though.

**Comment by ricksladkey** [comment]
@TKumadaki VsVim can readily tell the difference between <kbd>Tab</tab> and <kbd>Ctrl</kbd>+<kbd>I</kbd>, but vim is defined to behave so that they are interchangeable. As a result, you can cannot map them independently in VsVim because you cannot map them independently in vim.

In this particular case, @EdwinVanRooij already had a mapping for tab in his VsVim rc file:

```
nnoremap <tab> >>
```

and so that mapping overwrites any earlier mapping for the tab key.

**Comment by TKumadaki** [comment]
@ricksladkey
Thank you for correcting my mistake.
I have a lot to learn in VsVim and Vim.

**Comment by ricksladkey** [comment]
@TKumadaki Sorry, I was not trying to point out any mistake, but rather to clarify that the reason for the inability to distinguish between the keys is a **choice** that VsVim makes because it the project goal is, in as much as it is possible, to be compatible with vim.

As far as why vim behaves this way, the reason is that vim is designed to behave the same way over telnet / ssh (or even a serial port) as does for a native GUI application like gvim or VsVim. When you type the <kbd>Tab</kbd> key in an ssh session, the remote computer sees only the ASCII tab character, not that it was pressed by a key named `Tab`. So what you say is very much true for vim running over ssh: vim cannot distinguish between <kbd>Tab</kbd> and <kbd>Ctrl</kbd>+<kbd>I</kbd>.
