### ISSUE TITLE
In C++, CTRL-] opens the Find Symbol Results panel instead of going to the definition directly.

### ISSUE THREAD

**Issue by maximebl** [VsVim/VsVim#2535]
When I use CTRL-] in C++, visual studio 2017 opens a Find Symbols Results window instead of directly jumping to the definition. However if I use visual studio's F12 (Edit.GoToDefinition), it is able to jump directly to the definition.

Is there a workout to have CTRL-] have the some behavior as F12?

**Comment by ricksladkey** [comment]
@maximebl Ha, ha, that is a workaround from ages ago which no longer seems necessary. For example, see this old issue #1403 or this forum article from, wait for it, [2008](https://social.msdn.microsoft.com/Forums/vstudio/en-US/780862d6-aeb0-4822-b5e5-16e5342f2f4c/editgotodefinition-and-c-projects?forum=vcgeneral)!

Apparently, someone finally figured out C++ did it differently than everybody else and fixed it, but VsVim never noticed. I'll make sure that workaround is not used in versions of Visual Studio that don't require it.

In the meantime, you can map `<C-]>` directly to the "go to definition" command, but that isn't a perfect solution either because of the way that it handles the selection.

```
:nnoremap <C-]> :vsc Edit.GoToDefinition<CR>
```

or if you are using the vsixgallery version of VsVim:

```
:nnoremap <C-]> :vsc! Edit.GoToDefinition<CR>
```

**Comment by ricksladkey** [comment]
Ha, ha, the joke's on me because this is way more complicated than I thought and the same problem which led to the original workaround is still in effect in every version of Visual Studio include VS2019.

I should just delete my previous comment because practically everything I said is wrong! But a little humble pie is good so I will let it stand with this correction.

I will keep looking at this and trying to understand:

- How VsVim handles all of this right now
- Why `<C-]>` does not work the same as `F12`, even with the workarounds we have to try to make it work

**Comment by ricksladkey** [comment]
OK, I found the magic incantation that makes C++ 'go to definition' work like it does when you press `F12`, thanks to this StackOverflow question and answer:

- [How do I use DTE.ExecuteCommand(“Edit.GoToDefinition”) in a VS2010 C++ macro?
](https://stackoverflow.com/questions/20168945/how-do-i-use-dte-executecommandedit-gotodefinition-in-a-vs2010-c-macro)

I am working up a PR and will submit it when I finish.

**Comment by ricksladkey** [comment]
I hope I have redeemed myself with PR #2525. I'm using it in my test build and it is **awesome**. Furthermore, the `:vsc` command I suggested would now actually work instead of giving the dreaded "command expects one argument". This has been an ugly problem for VsVim for a **long** time and so I'm very happy to finally make some headway against it.
