### ISSUE TITLE
Search behavior has changed

### ISSUE THREAD

**Issue by jnothstine** [VsVim/VsVim#2536]
I used to be able to search for an item with / ? * or # and it works as expected.  Then, if I wanted to change search direction, I would press ? (in the case of a previous search with / ) and the search would go the opposite direction with the value of the previous search.  Now, when I press that ?, the contents of the search is blank and I have to hit up arrow also.  Same goes with any search and changing directions.

I checked with gvim and the behavior is as expected - what vsvim used to have.

**Comment by ricksladkey** [comment]
I can reproduce this bug at the head of master. As I do a lot of searching in my daily use of VsVim, you might have expected that I would also run into it. But I guess that in the same situation I usually use 'N' to search in the opposite direction. Who knows what my fingers do!

In any case, I know this used to work and so the task is to figure out which recent change caused the problem. In fact, I've just tested with VsVim 2.6.0 and it works correctly so the problem was introduced since the last Visual Studio Gallery release of VsVim.

**Comment by ricksladkey** [comment]
@jnothstine I would like to ask what you mean by:

> with `/?*` or `#`

Because the bug that I reproduced is just the normal `/[pattern]<CR>` followed by a bare reverse search `?<CR>` which reports:

```
Specified argument was out of the range of valid values.
Parameter name: searchPattern
```

but `?*` looks like it might be some special sequence that I don't know the meaning of.

**Comment by jnothstine** [comment]
I didn’t do a good job of explaining, sorry about that.

If I press * to search down for the word under the cursor and then press ? to go up, the bug shows itself.  I use this instead of N sometimes because I want to keep going the opposite direction of the search for a couple of times.

Sent from Mail for Windows 10

**Comment by ricksladkey** [comment]
@jnothstine Thanks, that's fine. Using `*` or `#` (or `g*` or `g#` for that matter) are things that should also work, but the basic `/` and `?` are broken as well. In my fix, I will test all of `/`, `?`, `*`, and `#`.

**Comment by jnothstine** [comment]
That sounds excellent, thank you!

Sent from Mail for Windows 10

**Comment by ricksladkey** [comment]
This appears to be some fallout from the recent PR #2472 to make search asynchronous. I've located the problem and I'll submit a fix.
