### ISSUE TITLE
Experimenting with Azure DevOps

### ISSUE THREAD

**Issue by jaredpar** [VsVim/VsVim#2557]
Part of completing #2549 meant that there is now an observable difference between our behaviors between VS2019 and VS2017 (and earlier). This means in order to full validate our build we essentially need to run tests twice. 

This makes sense conceptually. VsVim needs to run on different platforms with different behaviors. It makes sense to validate the implementation on each of those platforms. Up until now the behavior differences have been so small that there really wasn't a big risk here. But now with async completion, and the MEF composition fun, the gap feels very real. 

I'd been thinking of moving to Azure DevOps anyways. This type of dual testing is fairly easy to setup there. Wanted to do some experiments with this in order to see how it feels for VsVim.

While I'm doing this you may see some emails, or apps, showing up in the org related to this change. There will be a few PRs as well but they will be in draft mode and / or to branches under `/dev/jaredpar`. Those are meant to be experiments on my part to see how it all feels.

If it all feels good I'll send a PR to master representing the transition *proposal* that we can use as a decision point.

**Comment by ricksladkey** [comment]
This does not specifically relate to which back end CI is done on, but as far as testing, I have been running into very long test times compared to previous versions of VsVim and I was waiting for the release of 2.7.0 before I look any further into it.

Two testing issues I was hoping to address:

1. I think the tests mostly finish in a couple of minutes but actually take anywhere from 5 to 15 minutes depending on how they are run, that is from Visual Studio Test Explorer, from the command line, or via CI like appveyor. The problem seems to be WPF-related in that it has to do with the dispatcher and synchronization context emulation that we do during testing.  The goal is to run the tests as quickly as possible because ten minutes is too long!

2. Ideally, a developer could run **all** tests prior to pushing to a PR. If this requires that only VS2019 is a suitable platform for VsVim development, that seems like it would still be worth it.

**Comment by jaredpar** [comment]
@ricksladkey 

> The goal is to run the tests as quickly as possible because ten minutes is too long!

Agree. I've seen that happen a couple times but hadn't dug into it yet. Now that you mention it though I've seen it more recently on my laptop where I use Test Explorer exclusively. Wonder if that is the key ... Then again I use Test Explorer while working on Roslyn and VsVim shares the same WPF emulation layer and I don't see the issue there. Definitely should dig into this though and figure it out. 

> Ideally, a developer could run all tests prior to pushing to a PR

Completely agree. That is possible today but it's not obvious at all how to do it. Part of this work is making that simple + documenting how it works. 

> If this requires that only VS2019 is a suitable platform for VsVim development, that seems like it would still be worth it.

Don't think that will be necessary. The minimum requirements today are having .NET 4.7.2 and using the VS2017 tools / sdk. Those are sufficient to run the tests against the VS 2017 and VS 2019 editor. Further the VS2019 tools / sdk are compatible with the 2017 counterparts.

My plan is to use the VS2017 Azure Hosted image as a way to enforce that this continues to be true. That will allow for contributors to continue using VS2017 or VS2019 for development. At some point we'll move to deprecating VS2017 for contribution but hoping we can hold off on that a bit longer.

**Comment by ricksladkey** [comment]
Not to hijack this thread, but to at least finish the thought, I did get as far as watching the tests when run from the command line.  In that case, XUnit test runner actually prints out that it is completed, the number of tests, time to "completion" and then just sits there for a few more minutes using no CPU before exiting. I attached with the debugger and it is just waiting in the dispatcher. It eventually ends with a ThreadTerminate exception and then completes successfully.

So I really don't know what's going on, but to debug it further I thought I need to debug the XUnit test runner from source so I could see what was happening at the application domain loading / unloading level. Well, it turned out to be quite a project to get XUnit to build, but I did succeed at that eventually. However I haven't returned to trying to figure out why the tests don't finish properly.

**Comment by jaredpar** [comment]
@ricksladkey coincidentally ran into this today and it's puzzling. xunit is currently in the middle of unloading the `AppDomain` that is used to run the tests. The STA thread is inside `Dispatcher.Run` and the implementation is inside native code, specifically `GetMessageW`. 

That is blocking the `AppDomain` unload as it can't finish until all threads in the `AppDomain` complete and unload can't interrupt native code. 

It's strange. None of the other threads appear to be doing anything of note (even in native). Still digging .

**Comment by jaredpar** [comment]
@ricksladkey filed a separate bug for the test execution time issue. Had some time to debug last night. Got a bit more context into the problem. #2563
