### ISSUE TITLE
Clicking past end of file doesn't move cursor to end of file anymore

### ISSUE THREAD

**Issue by pierce-padi** [VsVim/VsVim#2586]
**Describe the bug**
When scrolling past the end of a file, clicking in the empty space underneath the source code doesn't move the cursor to the last line.

**To Reproduce**

1.  Go to any file
2.  Click in the empty area underneath the last line of code

**Expected behavior**
The cursor should move to the end of the file.

**Screenshots**
![image](https://user-images.githubusercontent.com/51244978/58727232-99327800-8398-11e9-85e1-cdd0cc391f56.png)
Clicking in the space underneath line 18 used to move the cursor to last line of code. Instead, the cursor stays where it's at (line 14 in this pic)

**Environment (please complete the following information):**

- Visual Studio version: 15.9.12
- VsVim version: 2.7.0.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**
This didn't happen with 2.6.0.0 and when disabling VsVim it works as expected.

**Comment by ricksladkey** [comment]
As long as by "the last line", you mean line 17, it is true that gvim in the same situation will move the caret to the beginning of line 17, which is the last line of the file. In VsVim 2.6.0 the caret would be moved to line 18, which is after the last line of the file. In VsVim 2.7.0 it does not move at all. I'll fix that.

**Comment by cheshire-howe** [comment]
Hi, you also changed entirely the way highlighting with the mouse works (I have a hybrid style, sorry to all about that).

I always start highlighting from the end of the block I want to grab and highlight in an upwards direction.
Before, I could click the end of line, then click it again, and that would move the cursor to the end of line. Then I would be able to highlight the same way a default text editor would. 
Now, there's no way to get the cursor over whether starting from command mode or insert mode. This means that highlighting will grab the new line character at the end of the line so grabbing chunks of code and moving them is nearly impossible with the mouse.

![image](https://user-images.githubusercontent.com/2804662/58833753-c2186e80-861f-11e9-89ee-fdddd2594bff.png)
When highlighting from anywhere right of the last character then moving up will have the visual block grab the newline character (the last blank blue block) instead of the old version where it was possible to _not_ grab the newline character.

**Comment by ricksladkey** [comment]
@cheshire-howe I'm really sorry for the "breaking changes" from the way Visual Studio handles the mouse to the way Vim handles the mouse.  In order for there to be a bug, we need to show a difference from how gvim behaves on the same file with the same settings. As far as I know, the mouse now behaves just like Vim. That said. the default way that Vim behaves may not be to your liking. Nevertheless, you find setting that help you achieve the mouse workflow you are trying to replicate.

I'm not 100% sure I understand your issue, but if you like the way Visual Studio handles the mouse, then you should probably use the settings:

```
behave mswin
set virtualedit=onemore
```

The former cause VsVim to use an inclusive selection and the latter allows you to place the mouse cursor after the last character of the line.

Hopefully you will be able to find settings to accommodate your needs. However, if you find any behavioral differences between the mouse handling of gvim and VsVim, please open an issue and I'll try to get it fixed quickly.

**Comment by cheshire-howe** [comment]
@ricksladkey Thanks for the quick reply. I know it's not a 'breaking change' it's just different. Thanks for the suggestion, I'm going to try them out right now :)

**Comment by cheshire-howe** [comment]
@ricksladkey Yep, worked perfectly. Thanks so much!
