### ISSUE TITLE
inoremap jk <ESC> works incorrectly

### ISSUE THREAD

**Issue by ant-222** [VsVim/VsVim#2624]
The command

    inoremap jk <ESC>

does not work in *VsVim* as it does in true *Vim*. When the sequence sequence *ijk* invoked in the middle of a line, it moves the cursor back one character in *Vim* but does not change its position in *VsVim*. The sequence *Ajk*, on the other hand, preserves the cursor position in *Vim*, but moves it to the start of the next line in *VsVim*.

**Comment by ricksladkey** [comment]
I cannot reproduce this issue. I can however reproduce the symptom using a different mapping:

```
inoremap jk <Esc><Right>
```

but that mapping behaves the same way in Vim as it does in VsVim.

I am guessing that somehow `<Right>` is being issued when leaving insert mode and that, furthermore, `whichwrap` includes the settings `:set whichwrap=<,>` (so that `<Right>` at the end of the line in normal mode will go to the next line).

@ant-222, could you retry your tests with no rc file? You can set up that condition by changing:

- Tools -> Options -> VsVim -> Defaults -> VimRc File Loading -> No vsvimrc or vimrc files

and then restarting Visual Studio.

**Comment by ant-222** [comment]
It indeed works correctly without an *rc* file, but my `.vsvimrc` is:

    set vsvim_useeditordefaults

    map gr :vsc Edit.FindAllReferences<CR>
    map gi :vsc Edit.GoToImplementation<CR>
    inoremap jk <ESC>

**Comment by ricksladkey** [comment]
OK, mystery solved. It turns out that you have a ASCII space after the closing angle bracket in your mapping. For better or worse, both VsVim and Vim interpret this space as part of the right hand side of the mapping. Furthermore, the default settings for `whichwrap` (again, in both VsVim and Vim) is `b,s` which means that a space at the end of the line will wrap onto the next line.

In short, everything is working correctly because both VsVim and Vim allow spaces in mappings. The problem is that a trailing space is not visible unless you have `:set list` turned on, and so it appears to be misbehaving.

**Comment by ant-222** [comment]
Thanks for the explanation, Rick. Case closed.
