### ISSUE TITLE
Could not open file "C:\Windows\System32\$VIMRUNTIME/vimrc_example.vim"

### ISSUE THREAD

**Issue by TerryTyson** [VsVim/VsVim#2639]
When I open a solution in VS 2019 I get this error:

```
Unknown function: has
Unknown option: compatible
Could not open file "C:\Windows\System32\$VIMRUNTIME/vimrc_example.vim"
Could not open file "C:\Windows\System32\$VIMRUNTIME/mswin.vim"
Unknown option: diffexpr
Error on line 66: Parse error
```

I was using VS 2017 and I believe this started with I switched to VS 2019. I tried uninstalling VsVim and re-installing it but the problem still remains. I am able to ignore the error and still work (including using VsVim) it is just annoying to keep getting this error and I can't figure out how to fix it.

- Visual Studio version: 2019 (16.1.3)
- VsVim version: 2.7.0.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

Thanks,
Terry

**Comment by jaredpar** [comment]
Wonder if this is related to #2585.

**Comment by TerryTyson** [comment]
@jaredpar yes, they are very closely related. The other issue concerns the reporting of the error whereas mine concerns what is causing the error.

**Comment by ricksladkey** [comment]
This problem occurs when you do not have a vsvim rc file but you do have a vim rc file. Previously VsVim would attempt to load your vim rc file, but would suppresses the reporting of any errors that you see. In VsVim 2.7.0, due to a bug, those errors (which always occurred), are now being reported.

To prevent these errors from being displayed you can:

1. Upgrade to the latest nightly build of VsVim (which includes a fix for that problem), or
2> You can create a vsvim rc file and only put in that file commands that VsVim understands.

The specific error you are getting is due to VsVim not expanding environment variables in the same situation that vim would expand them, but VsVim has always had that problem.

**Comment by TerryTyson** [comment]
@ricksladkey, thanks for the explanation. I upgraded to the latest build and that did the trick.
