### ISSUE TITLE
Mouse select and drag does not scroll

### ISSUE THREAD

**Issue by amoldeshpande** [VsVim/VsVim#2661]
**Describe the bug**

VsVim blocking scrolling+select

**To Reproduce**

Left-click anywhere in the editor window,drag down to select the text. Editor will stop scrolling when the mouse hits the bottom of the current view (sometimes it scrolls a bit further and then stops)

Disabling VsVim returns the functionality.

**Expected behavior**
I should be able to drag and select like my life depended on it.

**Screenshots**
None

**Environment (please complete the following information):**

- Visual Studio version: 2019
- VsVim version: 2.7.0.0
- Programming Language: C++
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by ricksladkey** [comment]
Yes, this was a side-effect of VsVim implementing **all** mouse functionality. Technically, this is not a bug from the point of view of parity with gvim because gvim doesn't auto-scroll in this way. However, I realize that all Windows users will expect this functionality from the editor.

When I get a chance, I will take a look at getting this implemented.

**Comment by ricksladkey** [comment]
Life was so simple when we were relying on native Visual Studio mouse support! Anyway, I'm glad you filed this issue because implementing it correctly was a fair amount of work that I might have skimped on, and I'm pretty pleased with the outcome now that it is really implemented.  Ha, ha, we can now truly say we have better mouse support than Vim itself! Well, at least as far as auto-scrolling is concerned...

**Comment by amoldeshpande** [comment]
Well, thank you for making the effort. I would have been sad if you had sacrificed Windows usability for gvim compatibility.
