### ISSUE TITLE
Not respecting turned off "Go to Definition" via mouse click with Ctrl

### ISSUE THREAD

**Issue by DominikJaniec** [VsVim/VsVim#2665]
**Describe the bug**
I very like to use standard VS behaviour of `Ctrl+MouseLeftClick` for fast and precise way of selecting whole "word", or words when dragging across of them. So, I always turn off VisualStudio's feature: _"Enable mouse click to perform Go to Definition"_.
Since some time I found that VS will sometimes navigate me to definition (which I don't want), however sometimes it will work as expected and select whole word. I was confident that it was some kind of glitch in VS 2019 Preview, as this feature was always disabled in my settings, and there were reported issues on auto turning it on. Then, I found this strange behaviour also on my private machine with VS 2017, and that let me find that this handy extension (without which I can not work) causes it :( and there is no UI options to manage it - turn off that behaviour.

**To Reproduce**
1. Configure VS (2017 / 2019) with _Go to Definition via mouse_ feature turn off, and open some C# sources solution.
2. Enter `insert` or `visual` mode of vi, and holding `ctrl` click on some types or drag over many words/lines.
3. Whole word(s) should be selected and no navigation should occur.
4. Change to `normal` mode, and when you click on something with `ctrl` being held, VS will try to go to definition, or even more annoying will alert you that it is impossible as keyword or bracket has been clicked.

**Expected behavior**
VsVim should respect this configuration, or allow to opt-out from this feature via UI.

**Screenshots**
Configuration:
![vs-config](https://user-images.githubusercontent.com/3832797/60462095-afa64a80-9c48-11e9-8076-162db19d7c94.png)

Annoying alert:
![vs-alert](https://user-images.githubusercontent.com/3832797/60462111-baf97600-9c48-11e9-9041-5635140538b2.png)

**Environment (please complete the following information):**
- Visual Studio version: 2017 (15.9.13), 2019 (16.1.4)
- VsVim version: 2.7.0.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [x] ReSharper - (VS2019) Yes / (VS2017) No, but it does not matter.
    - [ ] Visual Assist

**Comment by ricksladkey** [comment]
Thank you for taking the time to file a detailed report.

The Visual Studio setting you refer to controls how Visual Studios behaves when it handles mouse clicks. The state of this setting is internal to Visual Studio and so VsVim doesn't have direct access to it.

The current behavior for VsVim is compatible with Vim: `<C-LeftMouse>` is defined (see `:vimhelp <C-LeftMouse>`:

```
<C-LeftMouse>					*<C-LeftMouse>* *CTRL-]*
CTRL-]			Jump to the definition of the keyword under the
			cursor.  Same as ":tag {name}", where {name} is the
			keyword under or after cursor.
```

If you want to change the behavior in VsVim, you need to map control click to whatever you want it to do. For example:

```
noremap <C-LeftMouse> <Nop>
```

will disable that behavior.

Similarly, the way to select by word in Vim and VsVim with the mouse is to "double-click and drag" (see `:vimhelp <2-LeftMouse>`):

```
Dragging the mouse with a double click (button-down, button-up, button-down
and then drag) will result in whole words to be selected.  This continues
until the button is released, at which point the selection is per character
again.
```

To get the same effect in Vim or VsVim by using the control key (instead of double clicking), you can use the following mappings:

```
noremap <C-LeftMouse> <2-LeftMouse>
noremap <C-LeftDrag> <LeftDrag>
```
