### ISSUE TITLE
Inline rename is broken in F#

### ISSUE THREAD

**Issue by 333fred** [VsVim/VsVim#2670]
**Describe the bug**
When I attempt to rename a field in an F# program, the rename dialog pops up, but vsvim enters normal mode and does not allow for editing of any text. When edits are attempted, the rename is cancelled.

**To Reproduce**

1. Create a new F# console app.
2. `let test = ""`
3. Hit F2 on `test`. Inline rename pops up, and the variable is selected for a second, then vsvim enters normal mode, deselects the text, and moves the cursor past test. Any attempts to edit the text cancels the rename.

**Expected behavior**
Behavior identical to C#.

**Environment (please complete the following information):**

- Visual Studio version: 16.2.0 Public Preview 3
- VsVim version: 2.7.0.0
- Programming Language: F#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by ricksladkey** [comment]
This was a bug, but it was fixed in PR #2603 at the same time as the bug reported in your previous issue #2587. See:

- https://github.com/VsVim/VsVim/issues/2587#issuecomment-500098665

for my recommended settings.

I would very much appreciate if you would switch to the nightly builds:

- https://github.com/VsVim/VsVim/wiki/FAQ#how-can-i-install-a-build-with-the-latest-sources

and give the new behavior a test drive.

**Comment by 333fred** [comment]
Yep, updating to the nightlies fixed it. Thanks Rick!
