### ISSUE TITLE
Paste of multi-line visual block selection inserts into one line

### ISSUE THREAD

**Issue by mgregory22** [VsVim/VsVim#2694]
First off, great job on this project!  I freaking love it.  You guys are doing an outstanding job.

I noticed that selecting a visual block and pasting it doesn't insert into each line, but inserts it all into the first line.  For example, if you block-select all the instances of ' SELECT':
```
hello world SELECT
hello world SELECT
hello world SELECT
```

and delete:
```
hello world
hello world
hello world
```

then move the cursor to the 'o' of the first 'hello' and press 'p', it should look like this:
```
hello SELECT world
hello SELECT world
hello SELECT world
```

but instead looks like this:
```
hello SELECT
 SELECT
 SELECT world
hello world
hello world
```

**Comment by ricksladkey** [comment]
This seems to be an adverse side effect of the setting `:set clipboard=unnamed`. In my testing of VsVim 2.7.0, it works correctly with the setting `:set clipboard=`.

**Comment by ricksladkey** [comment]
P.S. Thanks for your kind words. I appreciate them and I know @jaredpar does too!

**Comment by mgregory22** [comment]
> This seems to be an adverse side effect of the setting `:set clipboard=unnamed`. In my testing of VsVim 2.7.0, it works correctly with the setting `:set clipboard=`.

You're right, I'm using clipboard=unnamed.  Thanks for the workaround!

**Comment by MRog40** [comment]
This is broken again, but in a slightly different way.

Starting with the same reference text as before:
```
hello world SELECT
hello world SELECT
hello world SELECT
```
With clipboard=unnamed, using <Ctrl-v> for visual block mode in VsVim, starting in normal mode with above text in buffer,
`gg$<Ctrl-v>jjbhybbep`

In Vim, the buffer now looks like
```
hello SELECT world SELECT
hello SELECT world SELECT
hello SELECT world SELECT
```
with this in your clipboard
```
 SELECT
 SELECT
 SELECT

```

Doing the same in Visual Studio, I actually realize another small issue: Vim puts the cursor at the top left of the visual block after yank, while VsVim puts it back at the start of the block in the top right. That isn't the big problem here though so moving past it by adding one `b` to the commands: `gg$<Ctrl-v>jjbhybbbep`
This leaves the buffer with:
```
hello SELECT
hello world SELECT
hello world SELECT world SELECT
hello world SELECT
hello world SELECT
```
and a clipboard with
```
 SELECT
hello world SELECT
hello world SELECT
```

It seems like it's treating the block as just a visual selection between the start and end of the selection, instead of as a visual block.
