### ISSUE TITLE
Hope to support " mark

### ISSUE THREAD

**Issue by XiaoXiaoLui** [VsVim/VsVim#2700]
**Feature category**
marks

""Vim feature**
In gVim, " mean the last cursor position when exiting current buffer.
But in vsvim, '" just go to the first line of current file.

**Is your feature request related to a problem? Please describe.**
I use this to quickly jump to file
noremap ,A 'A'"
After make a mark A at file XX, I can use ,A to jump to file XX at the last position when exiting the file.

**Describe the solution you'd like**
Support mark " like vim or is there other ways to do what I want?
I just want a file mark instead of file:position mark.

**Comment by ricksladkey** [comment]
In Vim and VsVim, the cursor position when last exiting a file is only updated when the last window for the buffer is closed. For example, if you close a Visual Studio document window, or if you issue `:q`, the position will be updated. But if you just switch windows, say, using `:tabn` or `:tabN` or <kbd>Ctrl</kbd>+<kbd>Tab</kbd>, the last exited position is not updated.

This is leading up to saying that if the `"` mark is set to the first line of the file, it generally means that the buffer has never been closed. The good news is that if the buffer is still open, your **current** buffer position is always "restored" automatically merely by switching to the buffer. In this case, it was never lost to begin with, it just wasn't visible.

This is all related to the fact that Vim can re-use the same window for different buffers, but VsVim never does that because it is not the way that the Visual Studio document model works.

As far as using a global mark as a synonym for a particular buffer without affecting the cursor position, I cannot think of a good way to do that because, at the moment, navigating to a global mark in VsVim does not update the jump list in the window of the buffer that was the target of the navigation. Offhand, I don't see any downsides to doing that, but I would like @jaredpar's opinion on the matter.

**Comment by ricksladkey** [comment]
@jaredpar This issue brings up another problem with the current VsVim architecture: mapped keystrokes are all processed by the same buffer even if part of the mapping switches to a different buffer. So even if the marks behaved differently, a mapping like this wouldn't work:

```
nnoremap <leader>A 'A'z
```

because the `'z` action would be executed in the buffer being switched from.

**Comment by jaredpar** [comment]
> This issue brings up another problem with the current VsVim architecture: mapped keystrokes are all processed by the same buffer even if part of the mapping switches to a different buffer.

Interesting. I hadn't thought of that possibility when I originally implemented the key mapping code. Definitely seems like a bug.

**Comment by ricksladkey** [comment]
The mark described in this issue is already implemented, but I've created a separate issue for the bug we found, issue #2704.
