### ISSUE TITLE
Using 'f', 't', 'F', 'T' to find multi-byte characters fails

### ISSUE THREAD

**Issue by MartinL0815** [VsVim/VsVim#2702]
**Describe the bug**
If a text contains e.g. German umlaute or other multi-byte characters (in UTF-8), the keys used to search forward or backward for a character to set the caret onto or "before" the searched character (f, F, t, T) fail.

**To Reproduce**

Searching forward:

1.  Enter a text with multi-byte characters like "Flügel"
2.  Place the caret at the start of the word
3.  Use 'f' or 't' to find 'ü'
4.  An error sound is played
5. VsVim expects another character to be entered

Searching backward:

1.  Enter a text with multi-byte characters like "Überschrift"
2.  Place the caret at the end of the word
3.  Use 'F' or 'T' to find 'Ü'
4.  An error sound is played
5. VsVim expects another character to be entered

**Expected behavior**
I expected the search-character-functions accessible via 'f', 'F', 't', and 'T' to set the caret to the position/offset of the searched multi-byte character.

**Environment (please complete the following information):**

- Visual Studio version: 2015/2017/2019
- VsVim version: 2.7.0.0
- Programming Language: independent
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by ricksladkey** [comment]
Ironically, this bug was introduced in PR #2516 when trying to fix a different problem (keystroke processing) on a different international keyboard (the Czech keyboard). That PR prevents normal mode from processing non-ASCII characters without bindings, which is correct except for the commands which accept an input character (e.g. `f``, `F`, `t`, `T` or `r`). I'll get this fixed ASAP!
