### ISSUE TITLE
Cursor (insertion point) invisible with custom Theme applied

### ISSUE THREAD

**Issue by Voxellence** [VsVim/VsVim#2714]
A complete description of the problem is posted [here](https://github.com/microsoft/VS-ColorThemes/issues/76).

1.  Go to 'Extensions->Manage Extensions' in Visual Studio 2019.
2.  Install the "Color Themes for Visual Studio" extension. Restart to complete installation.
3.  Go to 'Tools->Options...->Environment->General' and choose the "Mariana" theme next to "Color Theme:". Here you'll see that it looks nice.
4.  However, notice that in Normal Mode the cursor blinks, alternating between a white letter on a black background and no visible indication of a cursor at all.
5.  Press 'i' to enter Insert Mode. Notice that now that there is really no indication of an insertion cursor at all because it's black. When you move it to the right or the left, you can sometimes faintly see the cursor affecting a pixel or two of one letter. I've also noticed that the VsVim command bar is black text with a white background, which is as big of a deal since it's readable.

**Expected behavior**
I would expect the behavior to be the same as it is with the built-in Dark color theme. As you can see if you visit the link above, I have filed an issue at the VS-ColorThemes GitHub site, but I'm filing here as well in case there's something you're aware of that could easily fix this. I did try to edit the theme using the theme editor, but was unable to figure out how to fix the issue as I could not find any cursor property to modify.

- Visual Studio version: Visual Studio 2019 Professional
- VsVim version: 2.7.0.0
- Programming Language: C#, HTML, CSS
- Check(Type 'x') any that are installed:
    - [x] ReSharper
    - [ ] Visual Assist

Thanks in advance.

**Comment by Voxellence** [comment]
Okay, so I discovered that I should've been searching for "caret", not "cursor".

I filtered by "caret" and then modified the following properties to have these values:
Text Editor -> VsVim Block Caret -> Background = FFFFFFFF
Text Editor -> VsVim Block Caret -> Foreground = FF000000
This amounts to just reversing the black and white values.

This took care of the issue for both Normal and Insert modes of VsVim.

**Comment by ricksladkey** [comment]
VsVim uses its own caret foreground and background colors which are configured in Tools -> Options -> VsVim -> Defaults -> Item Colors. These colors do not adapt to any theming, but you can manually set them before or after changing the theme. The defaults are light theme friendly. When using a dark theme, you can simply switch foreground and background, or choose more specific colors.

It is not really possible to make the VsVim colors use the theme colors because Vim, unlike Visual Studio, uses a block caret. It is possible that VsVim could "guess" that the colors are bad and "fix" them, but at the moment, we have no plans to add such a capability.
