### ISSUE TITLE
[VSVim for Mac] Vim commands do not work on Xml files.

### ISSUE THREAD

**Issue by mandel-macaque** [VsVim/VsVim#2805]
**Describe the bug**
The vim plugin does not work with xml files (probably other no C# files too).

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a new xml file in a project/solution.
2. Try to use any vim command. Commands are ignored, we are always in insert mode.

**Expected behaviour**

Vim commands should work on xml files.

**Environment (please complete the following information):**

- Visual Studio version: Full version info can be found [here](https://gist.github.com/mandel-macaque/55b049af643f34e9de063e0206b1ff07).
- VsVim version: 2.8.0.4
- Programming Language: xml

**Comment by nosami** [comment]
Hi @mandel-macaque !

The reason that this extension doesn't work with xml files yet is because the old editor in VSMac is still being used for xml files and a couple of other file extensions (F# etc).

This is slated to change in VSMac 8.7

For now, you can install this older Vim extension that works with the old editor. Install via `Visual Studio -> Extensions -> Install from file`

https://github.com/nosami/XSVim/releases/download/0.65.11.81/XSVim.XSVim_0.65.11.81.mpack

<img width="672" alt="image" src="https://user-images.githubusercontent.com/667194/77394196-a8a30780-6d96-11ea-809b-2478336edb1d.png">
