### ISSUE TITLE
VsVim Mac - Intellisense doesn't pop up after character is typed

### ISSUE THREAD

**Issue by bysameng** [VsVim/VsVim#2832]
**Describe the bug**
First of all thank you for making this plugin nosami, I am a big fan.
It's really helped my work!

Unfortunately, I recently updated
- VsVim for Visual Studio Mac (2.8.0.8)
- Visual Studio Mac (8.6.2 build 6) Stable Channel

Now the Intellisense Auto Complete Window does not pop up when I am typing.
Intellisense still works when I hit Control+Space, and then the auto complete window pops up. I do have "Show completion list after a character is typed" enabled in settings.

**To Reproduce**

1. Use latest version of Visual Studio Mac and the VsVim plugin.
2. Open a C# solution. I am using a Unity project.
3. Type code, auto complete should pop up when characters are typed, but does not.
4. It does not pop up.
5. Click control+space. Auto complete does pop up.
6. Uninstall VsVim plugin.
7. Autocomplete works when characters are typed.

**Environment:**
- Visual Studio version: Visual Studio Mac 8.6.2 build 6 Stable Channel
- VsVim version: 2.8.0.8
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**
- macOS 10.15.5, all updates installed as of today.
Auto complete was working just before I updated my environment.

**I have tried**
- Reinstalling Visual Studio Mac
- Reinstalling the VsVim extension
- The Beta channel of Visual Studio Mac
- Rebooting my computer
- Other C# solutions
- Rebuilding the solution
Unfortunately the only way to get back the auto complete window when typing is to remove the VsVim plugin, so I assume the issue lies with this extension.

**Comment by nosami** [comment]
Can confirm, no idea what is wrong yet though - it only repros when I am not debugging.

**Comment by nosami** [comment]
@bysameng Seems like I had a bad build locally. This issue was introduced in 2.8.0.8

You can install 2.8.0.7 from https://addins.monodevelop.com/Stable/Mac/8.5.2/Vim.Mac.VsVim-2.8.0.7.mpack until I figure out the best way to fix this.

**Comment by nosami** [comment]
@jaredpar @ricksladkey Please can you give me some pointers here? I can't tell how this problem is handled on the Windows side. I'm not sure if this issue is due to some fundamental difference in how the keys are handled or if I am just missing something obvious.

The problem I am having is that I need Insert mode keys to be handled by VSVim so that Insert mode key remappings work and so that Insert mode keys are recorded as part of macros etc. But also, I need Insert mode keys to be handled by VSMac so that Intellisense works correctly.

If I force `e.Handled = false` to propagate the event and let the Intellisense mechanism handle the keypress, then the Intellisense popup displays but the keypress is inserted twice into the document.

I figure that it may be possible to force the trigger of the Intellisense popup window to open, but I don't see that happening anywhere on the Windows side (except for Word completions). Any solution that I think of seems pretty hacky.

Hope this made sense. Thanks in advance for any pointers.
