### ISSUE TITLE
Missing from VSMac extension gallery

### ISSUE THREAD

**Issue by ogirginc** [VsVim/VsVim#2837]
According to the https://github.com/VsVim/VsVim/wiki/MacOS-guide, searching for VSVim should show me the VsVim extentation. However, I can't find it when I have tried:

<img width="839" alt="Screenshot 2020-06-13 at 16 12 29" src="https://user-images.githubusercontent.com/7466873/84569642-f2493000-ad90-11ea-8aac-13227d2dd492.png">

As a dotnet newbie, am I missing something obvious here?

**Comment by nosami** [comment]
@ogirginc ugh, sorry about that. 

I removed the latest version 2.8.0.8 from the Gallery because of a bug, and for some reason, the previous version (2.8.0.7) doesn't get picked up.

You can use the `Install from file` button in your screenshot to install this https://addins.monodevelop.com/Stable/Mac/8.6/Vim.Mac.VsVim-2.8.0.7.mpack

Sorry for the delayed response, I'm currently on vacation and spending as little time as possible in front of the computer :)

**Comment by ogirginc** [comment]
> @ogirginc ugh, sorry about that.

No worries at all.

> You can use the Install from file button 

That's how I have done it. Thanks! :)

> Sorry for the delayed response, I'm currently on vacation and spending as little time as possible in front of the computer :)

Have a nice vacation! 🏖

**Comment by funseiki** [comment]
Just checking to see if there were any updates on this.

**Comment by nosami** [comment]
@funseiki I just published version 2.8.0.7 for VSMac 8.7 & 8.8

**Comment by funseiki** [comment]
Awesome, thanks!

**Comment by nosami** [comment]
Closing as this is resolved now.
