### ISSUE TITLE
How to install and run against VsMac 2022 17.3 Preview 5

### ISSUE THREAD

**Issue by coolbluewater** [VsVim/VsVim#2988]
I was able to run VSVim on VsMac 2022 17.3 Previews until Preview 3 by manually copying the VSVim package to the correct install folder. However in the last couple of previews the extension is listed as Disabled.

How do I get this beloved  extension working again? 😔

**Comment by nosami** [comment]
Hi @coolbluewater! This issue is fixed by https://github.com/VsVim/VsVim/pull/2987 but unfortunately I am having issues with CI that I haven't got around to resolving yet (I've been on a caravan holiday for a few days and I have no wifi or mobile signal - bliss :) )

If you trust me, you can use the following mpack file that I built myself on my machine. You will need to uninstall the version that you are currently using first as this pack file has an older version number.

https://github.com/nosami/nosami.github.io/raw/master/Vim.Mac.VsVim.0.8.0.15.mpack

If you don't trust me, you can build the code yourself in #2987 :)

**Comment by coolbluewater** [comment]
Unfortunately, I was unable to get this to work, most likely because my ad-hoc "uninstall" left traces of the old extension behind. Could you explain how to do this like you're speaking to a 5 year old? :)

**Comment by nosami** [comment]
> Unfortunately, I was unable to get this to work, most likely because my ad-hoc "uninstall" left traces of the old extension behind. Could you explain how to do this like you're speaking to a 5 year old? :)

> I was able to run VSVim on VsMac 2022 17.3 Previews until Preview 3 by manually copying the VSVim package to the correct install folder. However in the last couple of previews the extension is listed as Disabled.

^^ I'm not sure this is even supported. It might explain why you had issues removing it. The UI supports installing / uninstalling / enabling / disabling extensions again in the latest preview. I know it wasn't implemented for quite a while.

This is how you can install without using the UI. I know this isn't documented anywhere :)

```
/Applications/Visual\ Studio\ \(Preview\).app/Contents/MacOS/vstool setup install ~/src/Vim.Mac.VsVim_2.8.0.13.mpack
```

**Comment by SailDev** [comment]
Being on a floating caravan, i can confirm, that installing the .mpack download version works in VS for Mac 2022 17.4.

**Comment by nosami** [comment]
2.8.0.16 was just [released](https://github.com/VsVim/VsVim/releases/tag/v2.8.0.16-vsm17.3)

It should appear within the Extensions gallery within VSMac sometime today.
