### ISSUE TITLE
VsVim doesn't work at all

### ISSUE THREAD

**Issue by nightmareci** [VsVim/VsVim#2991]
**Describe the bug**
It doesn't work at all for me, and doesn't show any VsVim section in the Options menu, when installed from the Visual Studio extension manager.

**To Reproduce**
Just install the extension on latest Windows 10, Visual Studio Community 2022. Don't know if it's some weird issue that doesn't consistently happen on other systems.

**Environment:**
- Visual Studio version: Community 2022 64-bit 17.2.6
- VsVim version: 2.10.0.5

**Comment by jaredpar** [comment]
Sorry you're hitting this. It's likely something on your machine / instance of Visual Studio that is causing the issue here. Couple of steps to try here. 

1. Verify the extension is enabled: go to Extensions menu, look at Installed extension and verify that VsVim is both installed and enabled.
1. Uninstall / reinstall the extension

If those don't work there are other logs we can grab to see what is going on.

**Comment by nightmareci** [comment]
Well, I'm not really sure what fixed it, but now it's fixed and fully working. Before you replied, I did try uninstalling and reinstalling many times, with that never fixing it, but did it again after reading your reply, dug around in the install files myself to see if I could find some error messages but no errors looked to be present, then tried opening Visual Studio after that and it somehow magically was working. So, for those of you that have this issue, this post isn't terribly helpful, as I don't know exactly what fixed the issue now vs. my previous uninstall/reinstall attempts not working.
