### ISSUE TITLE
CTRL-E not working

### ISSUE THREAD

**Issue by rmclo** [VsVim/VsVim#608]
For awhile, CTRL-E did what I expected, namely scroll one line at a time while keeping my cursor on the same line.  Since the new release (not sure if it's 1.0 or the release before it) it behaves the same as CRTL-D, namely jumping the cursor down a half-page of text.

**Comment by mochsner** [comment]
Has anyone else has seen issues with this functionality in VS 2017 (Community)? Haven't been able to get this to work since installing, and the keybindings are definitely enabled (with VS rebooted multiple times). On version 15.89.17, but I suspect it could be something to do with conflicting plug-ins I'm using - will need to follow-up on that.

**Comment by oscarbailey-tc** [comment]
Just had this same issue, disabling the shortcut by looking in Options -> Environment -> Keyboard:

InteractiveConsole.ExecuteInInteractive

Worked for me!
