### ISSUE TITLE
vimrc no longer loading

### ISSUE THREAD

**Issue by boushley** [VsVim/VsVim#766]
I upgraded to version 1.2.0.0 and my _vimrc file stopped loading. I am running VisualStudio as Administrator, so I'm not sure if this could be causing the problem. I didn't move or change my _vimrc during the upgrade process. I have a _vsvimrc and _vimrc in my user directory, and the same files in C:\Program Files (x86)\Vim None of these files appears to be loading. I have to :set ignorecase and incsearch and highlight search each time I open VisualStudio.

VsVim version 1.2.0.0
VisualStudio 2010 SP1 version 10.0.40219.1
ReSharper 6.1.37.86

**Comment by Havebeard** [comment]
The issue seems to be back in 2.8.0.0

None of the lines with comments work:
`set ignorecase # ignore case in search
syntax on # highlight syntax
set number # show line numbers
set noswapfile # disable the swapfile
set hlsearch # highlight all results
set incsearch # show search results as you type
let mapleader = "'"
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv`

Everything works
`set ignorecase
syntax on
set number
set noswapfile
set hlsearch
set incsearch
let mapleader = "'"
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv
`
