### ISSUE TITLE
Ctrl-R to redo is not working in VsVim

### ISSUE THREAD

**Issue by wiserfirst** [VsVim/VsVim#784]
I'm using vs2010 + latest VsVim
Looks like vim Ctrl-R is working in VsVim?
When I press Ctrl-R, VS says: '(Ctrl-R) was pressed. Waiting for second key of chord...'
Note: I understand that there is an Option button in after the VsVim command line. But even if I choose to VsVim to handle Ctrl+R, VS is still handling Ctrl+R and complains: '(Ctrl+R) was pressed. Waiting for second key of chord...' I just tried to change this setting and let VS handle Ctrl+R, then change it back to VsVim. But still can't redo a previously undoed editting.
I wonder if this is what is expected (because Ctrl+R has not yet been implemented) or caused by my VS settings?

**Comment by theprash** [comment]
I'll put this here as it might be useful:

I had this problem on VS2015 and I started to try the solution above - deleting all of the `Ctrl-R` shortcuts. Most of mine were created by ReSharper and they were compound ones, e.g. `Ctrl-R, Ctrl-I`. I removed a few of these to no effect. Then I noticed that the `View.SolutionExplorer` command had just `Ctrl-R` as one of its shortcuts. Removing this one fixed the problem

**Comment by programus** [comment]
I have exactly the same problem on a Japanese VS 2010. I deleted all shortcut bound with Ctrl+R, it is not fixed. 
I wonder VS might always catch ctrl+R since it is possible for a Ctrl+R, XXXX shortcut combination.

**Comment by farzadmf** [comment]
I found a work-around for this problem. Since I'm so used to using `CTRL+R` for refactoring, I didn't want to change it, so I decided to map `CTRL+Y` to it. I added this line to my `~/_vimrc`:

    inoremap <C-Y> <C-r>

Now, if I press `CTRL+Y` in INSERT mode, I can then type the register name, and it will paste it. Helps me A LOT!

**Comment by vds2212** [comment]
> 
> 
> @jaredpar thanks for your reply.
> Maybe this is caused by a localization issue. But when I was trying to search the Internet for a solution to this issue, I also noticed a post on stackoverflow (http://stackoverflow.com/questions/8500229/how-to-redo-when-using-vsvim/9416430#9416430). So I suppose there might be some other people who are not using a simplified Chinese version of VS, but also have problem with Ctrl-R to redo.
> BTW: I update to the latest VsVim code from github at least once a week and build it myself. But I have to remove the current installation and then install the new version every time. So I wonder if there is any more convenient way to upgrade an existing VsVim installation.
> I really appreciate that you've done such a great job in providing a nice tool for development in Visual Studio!

The stackoverflow question [How to redo when using VsVim?](https://stackoverflow.com/questions/8500229/how-to-redo-when-using-vsvim/9416430#9416430) provide a solution to the problem.

Please read the remark of @NoSaidTheCompiler for a solution that works with recent version of VsVim and VisualStudio.

**Comment by kcbanner** [comment]
> I have exactly the same problem on a Japanese VS 2010. I deleted all shortcut bound with Ctrl+R, it is not fixed.
I wonder VS might always catch ctrl+R since it is possible for a Ctrl+R, XXXX shortcut combination.

I also observed some strange behaviour with Ctrl+R, and had difficulty unbinding the shortcuts.

Ctrl+R was not being captured by VsVim, even though Ctrl+R was set to VsVim in the VsVim -> Keyboard settings.

Testing Ctrl+R in the Environment -> Keyboard settings showed no shortcuts.

I set Ctrl+R back to Visual Studio in VsVim -> Keyboard. The tooltip here showed a bunch of bindings for `TestExplorer` commands that used `Ctrl+R, ...` combos, so I figured these binds were being hidden from the Environment -> Keyboard settings.

![image](https://github.com/user-attachments/assets/c7987ff7-3af2-43f9-9f08-f4ac0fb7fb19)

However, I have these "ghost" bindings that do not show up in the Keyboard screen, and that I couldn't remove.

Redo wasn't working with Ctrl+R, so (with Ctrl+R still set to VsVim), I bound Ctrl+R to Edit.Redo manually.

Redo now worked. However it seems that VsVim was never receiving Ctrl+R even though it was set to receive it. Perhaps these "ghost" bindings I have are interfering - it does seem that chord-style bindings block extensions from receiving the combo.
